In [1]:
#"TrainDataWithout2010.csv" is the csv file that the combination of all 8 csv files. Before running this cell please run:
'''LIST = []
for i in range(2011,2019):
    a = "{}DF.csv".format(i)
    LIST.append(pd.read_csv(a))
df = pd.concat(LIST,ignore_index=True)
df.to_csv("TrainDataWithout2010.csv.csv",index=False)'''
#You will also have this file in my GitHub.

In [2]:
import pandas as pd
df = pd.read_csv("TrainDataWithout2010.csv")

In [3]:
df

,Title,Worldwide,Budget,MPAA,Domestic Distributor,Domestic Opening,Genres
0,tt1201607,1.342322e+09,NaN,PG-13,Warner Bros.,169189427.0,"Adventure,Fantasy,Mystery"
1,tt1399103,1.123794e+09,195000000.0,PG-13,DreamWorks,97852865.0,"Action,Adventure,Sci-Fi"
2,tt1324999,7.122059e+08,110000000.0,PG-13,Summit Entertainment,138122261.0,"Adventure,Drama,Fantasy,Romance,Thriller"
3,tt1411697,5.867643e+08,80000000.0,R,Warner Bros.,85946294.0,Comedy
4,tt1298650,1.045714e+09,250000000.0,PG-13,Walt Disney Studios Motion Pictures,90151958.0,"Action,Adventure,Fantasy"
...,...,...,...,...,...,...,...
1595,tt3521126,2.982062e+07,NaN,R,A24,1211345.0,"Biography,Comedy,Drama"
1596,tt0062622,6.580250e+07,12000000.0,NaN,Metro-Goldwyn-Mayer (MGM),NaN,"Adventure,Sci-Fi"
1597,tt5080556,3.694597e+07,NaN,NaN,NaN,2775000.0,"Action,Sci-Fi"
1598,tt3741632,1.047218e+07,NaN,R,Sony Pictures Classics,NaN,"Adventure,Comedy,Drama,Romance"
1599,tt4971344,1.314306e+07,NaN,R,Annapurna Pictures,115575.0,"Crime,Drama,Western"

In [4]:
import numpy as np

In [5]:
YEARS = np.empty(1600)

In [6]:
YEARS[:200] = 2011
YEARS[200:400] = 2012
YEARS[400:600] = 2013
YEARS[600:800] = 2014
YEARS[800:1000] = 2015
YEARS[1000:1200] = 2016
YEARS[1200:1400] = 2017
YEARS[1400:1600] = 2018

# This is just for performance of the model, we write 1 instead of 2011 here.
YEARS = YEARS - 2010

In [7]:
df["Year"] = YEARS

In [8]:
df["Year"] = df["Year"].astype(np.int8)

In [33]:
df.to_csv("DF_With_YEARS.csv")